FROM python:3.11-slim@sha256:90edbeb8e4efce8dfe102f24c5ea1c8a1d770ff3d99c9c565d89ec97145f0fea
WORKDIR /app
COPY scripts/clamd_mock.py /app/clamd_mock.py
EXPOSE 3310
CMD ["python", "/app/clamd_mock.py"]
