import { Empty, Table, Tag, Typography } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import dayjs from 'dayjs'
import { Link } from 'react-router-dom'
import type { Ticket, TicketFilters } from '../types'
import { TicketStatusTag } from './TicketStatusTag'
const priority:Record<string,{label:string;color:string}>={normal:{label:'普通',color:'#167c72'},expedited:{label:'加急',color:'#c67513'},urgent:{label:'紧急',color:'#c43b3b'},major:{label:'重大事件',color:'#8b1e3f'}}
const sla:Record<string,{label:string;color:string}>={on_track:{label:'时限正常',color:'success'},due_soon:{label:'即将超时',color:'warning'},overdue:{label:'已超时',color:'error'},paused:{label:'计时暂停',color:'default'}}
export function TicketTable({items,total,loading,filters,onChange,basePath}:{items?:Ticket[];total?:number;loading:boolean;filters:TicketFilters;onChange:(next:TicketFilters)=>void;basePath:string}){const columns:ColumnsType<Ticket>=[{title:'工单编号',dataIndex:'ticket_id',width:166,render:v=><Link className="ticket-link" to={`${basePath}/${v}`}>{v}</Link>},{title:'分类',dataIndex:'category_name',width:130,render:v=>v||'待确认'},{title:'诉求摘要',dataIndex:'description',render:v=><div className="ticket-summary" title={v}>{v}</div>},{title:'状态',dataIndex:'status',width:100,render:(v,record)=><TicketStatusTag status={v} label={record.status_label}/>},{title:'优先级',dataIndex:'priority',width:96,sorter:true,render:v=><Typography.Text style={{color:priority[v]?.color,fontWeight:650}}>{priority[v]?.label||v}</Typography.Text>},{title:'SLA',dataIndex:'sla_state',width:104,render:v=><Tag color={sla[v]?.color}>{sla[v]?.label||v}</Tag>},{title:'催办',dataIndex:'reminder_count',width:72,render:v=>v?`${v} 次`:'—'},{title:'责任部门',dataIndex:'department_name',width:140,render:v=>v||'待派发'},{title:'创建时间',dataIndex:'created_at',width:170,sorter:true,render:v=>dayjs(v).format('YYYY-MM-DD HH:mm')}];const change=(page:TablePaginationConfig,_filters:unknown,sorter:unknown)=>{const s=sorter as {field?:string;order?:string};onChange({...filters,page:page.current,page_size:page.pageSize,sort:s.field==='updated_at'?'updated_at':s.field==='priority'?'priority':'created_at',order:s.order==='ascend'?'asc':'desc'})};return <Table rowKey="ticket_id" columns={columns} dataSource={items||[]} loading={loading} onChange={change} scroll={{x:1250}} locale={{emptyText:<Empty description="当前条件下暂无工单"/>}} pagination={{current:filters.page||1,pageSize:filters.page_size||20,total,showSizeChanger:true,showTotal:t=>`共 ${t} 条`}}/>}
