import { api } from './client'
import type { ApiSuccess, FeedbackRating, Priority, Ticket, TicketDetail, TicketFilters, TicketPage, WorkOrder, WorkOrderType } from '../types'
export const ticketKeys={all:['tickets'] as const,list:(f:TicketFilters)=>['tickets','list',f] as const,detail:(id:string)=>['tickets','detail',id] as const}
export async function listTickets(filters:TicketFilters){ return (await api.get<ApiSuccess<TicketPage>>('/tickets',{params:filters})).data.data }
export async function getTicket(id:string){ return (await api.get<ApiSuccess<TicketDetail>>(`/tickets/${id}`)).data.data }
export async function createTicket(payload:{idempotency_key:string;request_type:string;description:string;location:string;occurred_at_text?:string;target?:string;contact?:string;source:string}){return (await api.post<ApiSuccess<{ticket:Ticket;idempotent_replay:boolean}>>('/tickets',payload)).data.data}
export async function ticketAction(id:string,action:'accept'|'process'|'note',version:number,remark:string){ return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/${action}`,{version,remark})).data.data }
export async function acceptTicket(id:string,payload:{version:number;remark:string;category_id?:number;priority:Priority}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/accept`,payload)).data.data}
export async function assignTicket(id:string,payload:{version:number;remark:string;department_id:number;assigned_user_id?:number}){ return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/assign`,payload)).data.data }
export async function updateContact(id:string,payload:{version:number;remark:string;contact?:string}){ return (await api.patch<ApiSuccess<Ticket>>(`/tickets/${id}/contact`,payload)).data.data }
export async function resolveTicket(id:string,payload:{version:number;remark:string;resolution_summary:string;resolution_measures:string;resolution_outcome:string;public_reply:string;internal_note?:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/resolve`,payload)).data.data}
export async function rejectTicket(id:string,payload:{version:number;remark:string;reason_code:string;rejection_detail:string;suggested_channel?:string;needs_supplement:boolean}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/reject`,payload)).data.data}
export async function closeTicket(id:string,payload:{version:number;remark:string;override_reason:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/close`,payload)).data.data}
export async function submitTicketFeedback(id:string,payload:{version:number;rating:FeedbackRating;comment?:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/feedback`,payload)).data.data}
export async function pauseTicketSla(id:string,payload:{version:number;remark:string;reason:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/sla/pause`,payload)).data.data}
export async function resumeTicketSla(id:string,payload:{version:number;remark:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/sla/resume`,payload)).data.data}
export async function remindTicket(id:string,payload:{version:number;remark:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/remind`,payload)).data.data}
export async function requestTicketSupplement(id:string,payload:{version:number;remark:string;supplement_reason:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/supplement-request`,payload)).data.data}
export async function submitTicketSupplement(id:string,payload:{version:number;remark:string;supplement_content:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/supplement`,payload)).data.data}
export async function createWorkOrder(id:string,payload:{version:number;task_type:WorkOrderType;department_id:number;assignee_user_id?:number;instructions:string}){return (await api.post<ApiSuccess<WorkOrder>>(`/tickets/${id}/work-orders`,payload)).data.data}
export async function assignWorkOrder(ticketId:string,workOrderId:string,payload:{version:number;remark:string;assignee_user_id:number}){return (await api.post<ApiSuccess<WorkOrder>>(`/tickets/${ticketId}/work-orders/${workOrderId}/assign`,payload)).data.data}
export async function startWorkOrder(ticketId:string,workOrderId:string,payload:{version:number;remark:string}){return (await api.post<ApiSuccess<WorkOrder>>(`/tickets/${ticketId}/work-orders/${workOrderId}/start`,payload)).data.data}
export async function returnWorkOrder(ticketId:string,workOrderId:string,payload:{version:number;remark:string}){return (await api.post<ApiSuccess<WorkOrder>>(`/tickets/${ticketId}/work-orders/${workOrderId}/return`,payload)).data.data}
export async function transferWorkOrder(ticketId:string,workOrderId:string,payload:{version:number;remark:string;target_department_id:number;assignee_user_id?:number}){return (await api.post<ApiSuccess<WorkOrder>>(`/tickets/${ticketId}/work-orders/${workOrderId}/transfer`,payload)).data.data}
export async function submitWorkOrderResult(ticketId:string,workOrderId:string,payload:{version:number;remark:string;result_summary:string;result_measures:string;result_outcome:string;public_content:string;internal_note?:string}){return (await api.post<ApiSuccess<WorkOrder>>(`/tickets/${ticketId}/work-orders/${workOrderId}/submit`,payload)).data.data}
export async function summarizeTicket(id:string,payload:{version:number;remark:string;resolution_summary:string;resolution_measures:string;resolution_outcome:string;public_reply:string;internal_note?:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/summary`,payload)).data.data}
export async function reviewResolveTicket(id:string,payload:{version:number;remark:string;resolution_summary:string;resolution_measures:string;resolution_outcome:string;public_reply:string;internal_note?:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/review-resolve`,payload)).data.data}
export async function returnTicketToDepartment(id:string,payload:{version:number;remark:string;return_reason:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/return-to-department`,payload)).data.data}
export async function openTicketDispute(id:string,payload:{version:number;remark:string;dispute_reason:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/dispute`,payload)).data.data}
export async function resolveTicketDispute(id:string,payload:{version:number;remark:string;resolution:string;primary_work_order_id?:string}){return (await api.post<ApiSuccess<Ticket>>(`/tickets/${id}/dispute/resolve`,payload)).data.data}
