import { useMemo, useState } from 'react'
import { Avatar, Button, Dropdown, Grid, Layout, Menu, Space, Tag, Typography } from 'antd'
import { ApartmentOutlined, AuditOutlined, BarChartOutlined, BellOutlined, BookOutlined, BulbOutlined, CommentOutlined, CustomerServiceOutlined, DashboardOutlined, DatabaseOutlined, HomeOutlined, LogoutOutlined, MenuFoldOutlined, MenuUnfoldOutlined, SafetyOutlined, TeamOutlined, UnorderedListOutlined } from '@ant-design/icons'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import type { Role } from '../types'
const {Header,Sider,Content}=Layout
const roleLabels:Record<Role,string>={citizen:'市民',agent:'坐席',department_staff:'部门人员',admin:'管理员'}
const menuByRole:Record<Role,{key:string;icon:React.ReactNode;label:string}[]>={
 citizen:[{key:'/citizen/chat',icon:<CommentOutlined/>,label:'智能对话'},{key:'/citizen/policy',icon:<BookOutlined/>,label:'政策咨询'},{key:'/citizen/tickets',icon:<UnorderedListOutlined/>,label:'我的工单'},{key:'/citizen/intelligence',icon:<BulbOutlined/>,label:'智能诉求检查'},{key:'/citizen/notifications',icon:<BellOutlined/>,label:'通知中心'},{key:'/citizen/aftercare',icon:<CustomerServiceOutlined/>,label:'回访与申诉'}],
 agent:[{key:'/agent/tickets',icon:<UnorderedListOutlined/>,label:'待办与工单'},{key:'/agent/policy',icon:<BookOutlined/>,label:'政策辅助'},{key:'/agent/intelligence',icon:<BulbOutlined/>,label:'智能分派'},{key:'/agent/notifications',icon:<BellOutlined/>,label:'通知中心'},{key:'/agent/aftercare',icon:<CustomerServiceOutlined/>,label:'回访与申诉'}],
 department_staff:[{key:'/department/tickets',icon:<UnorderedListOutlined/>,label:'部门工单'},{key:'/department/kb',icon:<DatabaseOutlined/>,label:'政策知识库'},{key:'/department/intelligence',icon:<BulbOutlined/>,label:'文书辅助'},{key:'/department/notifications',icon:<BellOutlined/>,label:'通知中心'},{key:'/department/aftercare',icon:<CustomerServiceOutlined/>,label:'回访与申诉'}],
 admin:[{key:'/admin/dashboard',icon:<DashboardOutlined/>,label:'运营总览'},{key:'/admin/tickets',icon:<UnorderedListOutlined/>,label:'工单查询'},{key:'/admin/kb',icon:<DatabaseOutlined/>,label:'AI 知识库'},{key:'/department/kb',icon:<DatabaseOutlined/>,label:'文档管理'},{key:'/admin/ai-usage',icon:<SafetyOutlined/>,label:'AI 用量与安全'},{key:'/admin/intelligence',icon:<BulbOutlined/>,label:'智能与平台接入'},{key:'/admin/notifications',icon:<BellOutlined/>,label:'通知中心'},{key:'/admin/aftercare',icon:<CustomerServiceOutlined/>,label:'回访与申诉'},{key:'/admin/categories',icon:<ApartmentOutlined/>,label:'诉求分类'},{key:'/admin/users',icon:<TeamOutlined/>,label:'用户管理'},{key:'/admin/departments',icon:<HomeOutlined/>,label:'部门管理'},{key:'/admin/audit',icon:<AuditOutlined/>,label:'审计日志'}]
}
export function WorkspaceLayout(){const {user,logout}=useAuth();const nav=useNavigate();const loc=useLocation();const screens=Grid.useBreakpoint();const [collapsed,setCollapsed]=useState(false);const items=useMemo(()=>user?menuByRole[user.role]:[],[user]);if(!user)return null;const mobile=!screens.lg;return <Layout style={{minHeight:'100vh'}}><a className="skip-link" href="#main-content">跳到主要内容</a><Sider className="app-sider" width={232} collapsible collapsed={collapsed} onCollapse={setCollapsed} breakpoint="lg" collapsedWidth={mobile?0:72} trigger={null}><div className="brand"><div className="brand-mark">倾</div>{!collapsed&&<div><div className="brand-title">倾听助手</div><div className="brand-sub">TINGTING ASSISTANT</div></div>}</div><Menu theme="dark" mode="inline" selectedKeys={[items.find(x=>loc.pathname.startsWith(x.key))?.key||loc.pathname]} items={items} onClick={({key})=>nav(key)}/></Sider><Layout><Header className="app-header">{mobile?<Button className="mobile-trigger" type="text" icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(v=>!v)}/>:<Space><BarChartOutlined style={{color:'#167c72'}}/><Typography.Text type="secondary">政务诉求协同服务平台</Typography.Text></Space>}<Dropdown menu={{items:[{key:'logout',icon:<LogoutOutlined/>,label:'退出登录',onClick:()=>{nav('/login',{replace:true,state:null});logout()}}]}}><Button type="text" className="account-menu-trigger"><Space><Avatar style={{background:'#167c72'}}>{user.display_name.slice(0,1)}</Avatar><span>{user.display_name}</span><Tag>{roleLabels[user.role]}</Tag></Space></Button></Dropdown></Header><Content id="main-content" className="app-content"><Outlet/></Content></Layout></Layout>}
