import { useState } from 'react'
import { Alert, Button, Card, Descriptions, Empty, Form, Input, List, Modal, Radio, Select, Space, Statistic, Tag, Timeline, Typography, message } from 'antd'
import { CustomerServiceOutlined, FileProtectOutlined, PhoneOutlined, RedoOutlined, SafetyCertificateOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import dayjs from 'dayjs'
import { aftercareKeys, createAppeal, listAppeals, listFollowUps, recordPhoneFollowUp, reviewAppeal } from '../api/aftercare'
import { useAuth } from '../auth/AuthContext'
import type { Appeal, FollowUpTask } from '../types'
import { PageHeader } from '../components/PageHeader'
import { ErrorState } from '../components/ErrorState'

const appealLabels:Record<string,string>={submitted:'待审核',approved:'审核通过',rejected:'已驳回',reprocessing:'重新办理中',completed:'申诉处理完成'}
const appealColors:Record<string,string>={submitted:'gold',approved:'green',rejected:'red',reprocessing:'blue',completed:'cyan'}
const taskLabels:Record<string,string>={pending:'待回访',in_progress:'继续回访',completed:'已完成',cancelled:'已取消'}
const contactLabels:Record<string,string>={reached:'已接通',no_answer:'无人接听',wrong_number:'号码有误'}
const outcomeLabels:Record<string,string>={confirmed:'确认办结',needs_followup:'继续回访',appeal_requested:'市民拟申诉'}

export function AftercarePage(){
  const {user}=useAuth();const qc=useQueryClient();const [appealOpen,setAppealOpen]=useState(false);const [reviewing,setReviewing]=useState<Appeal|null>(null);const [calling,setCalling]=useState<FollowUpTask|null>(null);const [appealForm]=Form.useForm();const [reviewForm]=Form.useForm();const [callForm]=Form.useForm();const canCall=user?.role==='agent'||user?.role==='admin';const canReview=user?.role==='admin'
  const appeals=useQuery({queryKey:aftercareKeys.appeals,queryFn:()=>listAppeals()})
  const tasks=useQuery({queryKey:aftercareKeys.followups,queryFn:()=>listFollowUps(),enabled:canCall})
  const createMutation=useMutation({mutationFn:(values:{ticket_id:string;reason:string;desired_resolution:string})=>createAppeal(values.ticket_id.trim(),values),onSuccess:()=>{message.success('申诉已提交，将进入审核');setAppealOpen(false);appealForm.resetFields();qc.invalidateQueries({queryKey:aftercareKeys.appeals})}})
  const reviewMutation=useMutation({mutationFn:(values:{decision:'approved'|'rejected';review_comment:string;reprocess_instructions?:string})=>reviewAppeal(reviewing!.id,values),onSuccess:()=>{message.success('申诉审核已完成');setReviewing(null);reviewForm.resetFields();qc.invalidateQueries({queryKey:aftercareKeys.appeals})}})
  const callMutation=useMutation({mutationFn:(values:{contact_result:string;satisfaction?:string;outcome:string;notes:string})=>recordPhoneFollowUp(calling!,values),onSuccess:()=>{message.success('电话回访记录已保存');setCalling(null);callForm.resetFields();qc.invalidateQueries({queryKey:aftercareKeys.followups})}})
  const appealsError=appeals.isError
  return <div><PageHeader eyebrow="FOLLOW-UP & APPEAL" title="回访与申诉" description={user?.role==='citizen'?'提交正式申诉并跟踪审核、重新办理和处理结果。':'跟踪回访任务、申诉审核与重新办理闭环。'} extra={user?.role==='citizen'?<Button type="primary" icon={<FileProtectOutlined/>} onClick={()=>setAppealOpen(true)}>提交申诉</Button>:undefined}/>
    <section className="aftercare-summary" aria-label="业务规则摘要"><Card><Statistic title="申诉次数上限" value={2} suffix="次/工单" prefix={<SafetyCertificateOutlined/>}/></Card><Card><Statistic title="申诉期限" value={15} suffix="天" prefix={<FileProtectOutlined/>}/></Card><Card><Statistic title="自动回访时限" value={48} suffix="小时" prefix={<CustomerServiceOutlined/>}/></Card></section>
    <Alert className="aftercare-rule" showIcon type="info" message="状态规则" description="处理完成后自动进入回访；申诉审核通过即进入重新办理，重新出具结果后申诉完成。同一工单只能存在一个处理中申诉。"/>
    {canCall&&<section aria-labelledby="follow-up-heading"><div className="section-heading"><div><Typography.Title id="follow-up-heading" level={3}>自动回访任务</Typography.Title><Typography.Text type="secondary">坐席记录电话触达；确认满意可直接办结，未接通则保留继续回访。</Typography.Text></div><Tag icon={<PhoneOutlined/>}>{tasks.data?.total||0} 个任务</Tag></div>{tasks.isError?<ErrorState error={tasks.error} retry={()=>{void tasks.refetch()}}/>:<div className="follow-up-grid">{tasks.isLoading?<Card loading/>:(tasks.data?.items.length?tasks.data.items.map(task=><Card key={task.id} className={`follow-up-card status-${task.status}`} title={<Space><a href={`/${user?.role}/tickets/${task.ticket_id}`}>{task.ticket_id}</a><Tag color={task.status==='pending'?'gold':task.status==='in_progress'?'blue':'default'}>{taskLabels[task.status]}</Tag></Space>} extra={<Typography.Text type="secondary">第 {task.handling_round} 轮</Typography.Text>}><Descriptions size="small" column={1} items={[{key:'due',label:'最迟回访',children:dayjs(task.due_at).format('YYYY-MM-DD HH:mm')},{key:'records',label:'已记录',children:`${task.records.length} 次`} ]}/>{task.records.length>0&&<Timeline className="follow-up-history" items={task.records.slice(0,3).map(record=>({children:<><b>{contactLabels[record.contact_result]} · {outcomeLabels[record.outcome]}</b><br/><span>{record.notes}</span></>}))}/>}<Button block type={task.status==='pending'?'primary':'default'} icon={<PhoneOutlined/>} disabled={['completed','cancelled'].includes(task.status)} onClick={()=>setCalling(task)}>记录电话回访</Button></Card>):<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={<div><div>暂无回访任务</div><Typography.Text type="secondary" style={{fontSize:12}}>工单"处理完成"(resolved)后会自动创建回访任务,48 小时内需联系市民</Typography.Text></div>}/>)}</div>}</section>}
    <section aria-labelledby="appeal-heading"><div className="section-heading"><div><Typography.Title id="appeal-heading" level={3}>市民申诉</Typography.Title><Typography.Text type="secondary">全程保留申请、审核、重新办理与结果记录。</Typography.Text></div><Tag icon={<RedoOutlined/>}>{appeals.data?.total||0} 条申诉</Tag></div>{appealsError?<ErrorState error={appeals.error} retry={()=>{void appeals.refetch()}}/>:<List className="surface appeal-list" loading={appeals.isLoading} dataSource={appeals.data?.items||[]} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={<div><div>暂无申诉记录</div><Typography.Text type="secondary" style={{fontSize:12}}>市民对处理结果不满意时,可在处理完成或办结后 15 天内提交申诉,同一工单最多 2 次</Typography.Text></div>}/>}} renderItem={item=><List.Item actions={canReview&&item.status==='submitted'?[<Button key="review" type="primary" onClick={()=>setReviewing(item)}>审核申诉</Button>]:[]}><List.Item.Meta avatar={<div className="appeal-sequence">{item.sequence}</div>} title={<Space wrap><Typography.Text strong>{item.appeal_no}</Typography.Text><Tag color={appealColors[item.status]}>{appealLabels[item.status]}</Tag><Typography.Link href={`/${user?.role==='department_staff'?'department':user?.role}/tickets/${item.ticket_id}`}>{item.ticket_id}</Typography.Link></Space>} description={<div className="appeal-copy"><p><b>申诉理由：</b>{item.reason}</p><p><b>期望处理：</b>{item.desired_resolution}</p>{item.review_comment&&<p><b>审核意见：</b>{item.review_comment}</p>}{item.result_summary&&<p className="appeal-result"><b>申诉结果：</b>{item.result_summary}</p>}<Typography.Text type="secondary">提交于 {dayjs(item.created_at).format('YYYY-MM-DD HH:mm')}</Typography.Text></div>}/></List.Item>}/>}</section>
    <Modal title="提交市民申诉" open={appealOpen} onCancel={()=>setAppealOpen(false)} onOk={()=>appealForm.submit()} okText="确认提交" confirmLoading={createMutation.isPending} destroyOnHidden><Form form={appealForm} layout="vertical" onFinish={values=>createMutation.mutate(values)}><Alert type="warning" showIcon message="同一工单最多申诉 2 次；请在处理完成或办结后 15 天内提交。"/><Form.Item name="ticket_id" label="工单编号" rules={[{required:true,message:'请输入工单编号'},{pattern:/^QT\d{16}$/,message:'请输入有效工单编号'}]}><Input placeholder="QT2026071400000001"/></Form.Item><Form.Item name="reason" label="申诉理由" rules={[{required:true,min:10,message:'请至少填写 10 个字'}]}><Input.TextArea rows={4}/></Form.Item><Form.Item name="desired_resolution" label="期望处理方式" rules={[{required:true,min:4,message:'请说明期望处理方式'}]}><Input.TextArea rows={3}/></Form.Item></Form></Modal>
    <Modal title="申诉审核" open={!!reviewing} onCancel={()=>setReviewing(null)} onOk={()=>reviewForm.submit()} okText="提交审核" confirmLoading={reviewMutation.isPending} destroyOnHidden><Form form={reviewForm} layout="vertical" initialValues={{decision:'approved'}} onFinish={values=>reviewMutation.mutate(values)}><Form.Item name="decision" label="审核决定" rules={[{required:true}]}><Radio.Group><Radio value="approved">审核通过并重新办理</Radio><Radio value="rejected">驳回申诉</Radio></Radio.Group></Form.Item><Form.Item name="review_comment" label="审核意见" rules={[{required:true,min:4,message:'请填写审核意见'}]}><Input.TextArea rows={3}/></Form.Item><Form.Item noStyle shouldUpdate={(a,b)=>a.decision!==b.decision}>{({getFieldValue})=>getFieldValue('decision')==='approved'?<Form.Item name="reprocess_instructions" label="重新办理要求" rules={[{required:true,min:4,message:'请填写重新办理要求'}]}><Input.TextArea rows={3}/></Form.Item>:null}</Form.Item></Form></Modal>
    <Modal title="记录电话回访" open={!!calling} onCancel={()=>setCalling(null)} onOk={()=>callForm.submit()} okText="保存记录" confirmLoading={callMutation.isPending} destroyOnHidden><Form form={callForm} layout="vertical" initialValues={{contact_result:'reached',outcome:'confirmed',satisfaction:'satisfied'}} onFinish={values=>callMutation.mutate(values)}><Form.Item name="contact_result" label="联系结果" rules={[{required:true}]}><Select options={[{value:'reached',label:'已接通'},{value:'no_answer',label:'无人接听'},{value:'wrong_number',label:'号码有误'}]}/></Form.Item><Form.Item name="satisfaction" label="满意度"><Select allowClear options={[{value:'satisfied',label:'满意'},{value:'mostly_satisfied',label:'基本满意'},{value:'dissatisfied',label:'不满意'}]}/></Form.Item><Form.Item name="outcome" label="回访结论" rules={[{required:true}]}><Select options={[{value:'confirmed',label:'确认结果并办结'},{value:'needs_followup',label:'需要继续回访'},{value:'appeal_requested',label:'市民表示将申诉'}]}/></Form.Item><Form.Item name="notes" label="回访记录" rules={[{required:true,min:4,message:'请填写完整回访记录'}]}><Input.TextArea rows={4}/></Form.Item></Form></Modal>
  </div>
}
